language: php
php:
  - '7.3'
git:
  submodules: false

cache:
  bundler: true
  directories:
  - $HOME/.composer/cache/files
  - $HOME/node_modules

branches:
  only: [master]

before_install:
  - composer global require drupal/coder dealerdirect/phpcodesniffer-composer-installer squizlabs/php_codesniffer

script:
  - set +e
  - composer global exec -v --  "phpcs --standard=$TRAVIS_BUILD_DIR/phpcs.ruleset.xml --extensions=php $TRAVIS_BUILD_DIR/plugin.php"
  - composer global exec -v --  "phpcs --standard=$TRAVIS_BUILD_DIR/phpcs.ruleset.xml --extensions=php $TRAVIS_BUILD_DIR/src/"
